spring.application.name=flytrack

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.profiles.active=dev

brevo.api.key=${BREVO_API_KEY}

